### ISSUE TITLE
null orgs() handler needed for ResumeController

### ISSUE THREAD

**Issue by shuye02** [Computerization/sam#6]
`Call to a member function orgs() on null` when visiting `/resume/control`

![image](https://user-images.githubusercontent.com/22615765/48539459-1e20dd00-e8f2-11e8-98ec-124a38662326.png)

**Comment by davidzyc** [comment]
Because the Resume function is designed to enable sending without login, the logic add risks to SAM. **It is an obsolete function waiting to be removed. Personal information will be stored in another table in one_to_one relation to user table.**

**Comment by shuye02** [comment]
Maybe we should; actually I'm thinking about re-developing **a new platform with better managed submodules** and migrate all the data to the new platform

**Comment by davidzyc** [comment]
@shuye02 Great to hear it. With more and more modules added to SAM, it's increasingly difficult to maintain. Maybe we can turn SAM main site to a CAS site (Central Authentication System), and all other modules get authentication from CAS via oauth2. It's a lot work on re-writing the code but worth it. That's how modern large scale website works. The current architecture of SAM is the technology of 2010s, obsolete ones from ten years ago.

**Comment by davidzyc** [comment]
@shuye02 like how google account works. Login one time and use it in any google service every time.

**Comment by shuye02** [comment]
Closing this issue and starting new projects based on decentralized modules communicating through OAuth2.

You can track the changes [here in the organization project board](https://github.com/orgs/Computerization/projects/1)
